---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "10"

bases:
  # Assisted Installer Agent Configuration
  - ../../../base/configs/assisted-installer

resources:
