---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-hook-presync-csv-0.yaml
  - 00-hook-presync-csv-1.yaml
  - 01-ai-pull-secret.yaml
  - 01-assisted-service-config.yaml
  - 01-mirror-registry-ca.yaml
  - 02-agentserviceconfig.yaml
