---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "20"

bases:
  # Operators for MGMT Clusters
  - ../../../blueprints/mgmt/round-002

resources:
