---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
   name: openshift-v4.8.10-mirror
spec:
   releaseImage: lab-registry.ocpsmc.lab.diktio.net/nsatsia/ocp4810:4.8.10-x86_64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-config-map
  namespace: assisted-installer
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDlDCCAnygAwIBAgIBATANBgkqhkiG9w0BAQsFADA5MRcwFQYDVQQKDA5MQUIu
    RElLVElPLk5FVDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE5
    MDMxMDAzNDM0MloXDTM5MDMxMDAzNDM0MlowOTEXMBUGA1UECgwOTEFCLkRJS1RJ
    Ty5ORVQxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAOEatwt8carWOdYsAoh8BSMg5tUZmU+rUe1L
    fZKN6tA9ytpg4PqWaTRA8eXPfkyzpunf8NXmP1AWSf8LBH5fWUVxzFgmOfyrZroN
    9sLjf+ueuh+LK7tixL56aUkx0fjQecoBpD5rq4JUemjC1QocpHAVZeYkDlvuoXEq
    uhwj1/Dla5JI5YlEeD2AzvNNxjM3s23L+wfvPErKzbbamxFKZQPxCyPCom0Vm7hO
    47WJ6RgVKMlCQGx2zcw8ckS3mj9DJwhHTAcNAdBJyK6AD4PDmk/L7pVYyS6HtCTj
    NKAeedKqLFFGNvTkGCTBMA0aDwn5D1Ti9nqTG9tDm6a8PBmJWk0CAwEAAaOBpjCB
    ozAfBgNVHSMEGDAWgBQK1MC5fwTjULrfW5Z4vY82fnGcNjAPBgNVHRMBAf8EBTAD
    AQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUCtTAuX8E41C631uWeL2PNn5x
    nDYwQAYIKwYBBQUHAQEENDAyMDAGCCsGAQUFBzABhiRodHRwOi8vaXBhLWNhLmxh
    Yi5kaWt0aW8ubmV0L2NhL29jc3AwDQYJKoZIhvcNAQELBQADggEBAIJ4Hd2BjDK1
    tbeOp0TCmh3V59gaB4RTUQ8eDHKinqzglfWfvg6KsWMAENVRkjBqtEu7YwzMU5jx
    imV/nV7B6euftOLlg3L6uHJyUyqdsb9e8rN2Lt2Zho4e6i726g9FRCVXMNaQVFA4
    6rVNmIrAc88NGffiYxa1ANEfkqbD0RZYggxVBeN5l4C5QVZO/XdQLeUvQaFZir+R
    5ieeL2Zp5BObGec6tWYaAjJwlE5YMQh6IvQQgUfVMGCFrPwdN3KP2jEXW91Dy3rn
    WFBk6T3neXntdKX5ZipQM6qfFbH8DoDdElCvqZkB2bc1AwWaFzYbiEjz0oeowpUw
    tEChGIzF/34=
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["lab-registry.ocpsmc.lab.diktio.net"]

    [[registry]]
       prefix = ""
       location = "quay.io/openshift"
       mirror-by-digest-only = false

       [[registry.mirror]]
       location = "lab-registry.ocpsmc.lab.diktio.net/nsatsia"
    [[registry]]
       prefix = ""
       location = "quay.io/ocpmetal"
       mirror-by-digest-only = false

       [[registry.mirror]]
       location = "lab-registry.ocpsmc.lab.diktio.net/nsatsia"
    [[registry]]
       prefix = ""
       location = "quay.io/openshift-release-dev/ocp-release"
       mirror-by-digest-only = false

       [[registry.mirror]]
       location = "lab-registry.ocpsmc.lab.diktio.net/nsatsia/ocp4810"
    [[registry]]
       prefix = ""
       location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
       mirror-by-digest-only = false

       [[registry.mirror]]
       location = "lab-registry.ocpsmc.lab.diktio.net/nsatsia/ocp4810"
